apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  labels:
    elemental.cattle.io/managed-os-version-name: baremetal-v2.1.3-4.37-os
  name: os-upgrade
  namespace: fleet-default
spec:
  clusterTargets: []
  drain:
    deleteLocalData: true
    force: true
    ignoreDaemonSets: true
    skipWaitForDeleteTimeout: 60
  managedOSVersionName: baremetal-v2.1.3-4.37-os
