apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name: os-upgrade-test
  namespace: fleet-default
spec:
  clusterTargets: 
    - clusterName: test-el-cluster
  drain:
    deleteLocalData: true
    force: true
    ignoreDaemonSets: true
    skipWaitForDeleteTimeout: 60
  managedOSVersion: baremetal-v2.1.3-4.37-os
