apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-demo-app
  name: demo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-demo-app
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-demo-app
      namespace: default
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: '/usr/share/nginx/html/'
              name: vol-xaand
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sh
            - '-c'
            - echo "my name is $HOSTNAME" > /usr/share/nginx/html/index.html
          image: busybox
          imagePullPolicy: Always
          name: container-1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: '/usr/share/nginx/html/'
              name: vol-xaand
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: vol-xaand
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/demo-app"]'
  name: demo-app
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-demo-app
  type: ClusterIP
          
